# Generated by Django 6.0.5 on 2026-05-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=3)),
                ('email', models.EmailField(max_length=150)),
                ('passwd', models.CharField(max_length=100)),
            ],
        ),
    ]
